TNLBook/Models/CHUDE.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TNLBook.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CHUDE
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CHUDE()
        {
            this.SACHes = new HashSet<SACH>();
        }
    
        public int MaCD { get; set; }
        public string TenChuDe { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<SACH> SACHes { get; set; }
    }
}

TNLBook/Controllers/BuyController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TNLBook.Models;

using PagedList;
using PagedList.Mvc;
namespace TNLBook.Controllers
{
    public class BuyController : Controller
    {
        SaleBookEntities1 db = new SaleBookEntities1();
        // GET: Buy
        private List<SACH> Laysachmoi(int count)
        {
            // Sắp xếp theo ngày cập nhật, sau đó lấy top @count
            return db.SACHes.OrderByDescending(a => a.Ngaycapnhat).Take(count).ToList();
        }
        public ActionResult Index(int? page)
        {
            // tạo biến quy định trên mỗi trang
            int pageSize = 6;
            // tạo biến số trang
            int pageNum = (page ?? 1);

            var ds = Laysachmoi(18);
            return View(ds.ToPagedList(pageNum, pageSize));
        }

        [HttpGet]
        public ActionResult Detail(int id)
        {
            SACH sach = db.SACHes.Find(id);
            return View(sach);
        }

        [HttpPost]
        public ActionResult Detail(FormCollection f)
        {
            int masach = Int32.Parse(f.Get("Masach"));
            SACH sach = db.SACHes.Find(masach);
            sach.Tensach = f.Get("Tensach");
            sach.Giaban = Decimal.Parse(f.Get("Giaban"));
            sach.Mota = f.Get("Mota");
            sach.Anhbia = f.Get("Anhbia");
            sach.Ngaycapnhat = DateTime.Parse(f.Get("Ngaycapnhat"));
            sach.Soluongton = Int32.Parse(f.Get("Soluongton"));
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Chude()
        {
            var chude = from CHUDE in db.CHUDEs select CHUDE;
            return PartialView(chude);
        }

        public ActionResult SPTheochude(int id)
        {
            var sachCD = from SACH in db.SACHes where SACH.MaCD == id select SACH;
            return PartialView(sachCD);
        }

        public ActionResult NXB()
        {
            var nxb = from NHAXUATBAN in db.NHAXUATBANs select NHAXUATBAN;
            return PartialView(nxb);
        }

        public ActionResult SPTheoNXB(int id)
        {
            var sachNXB = from SACH in db.SACHes where SACH.MaNXB == id select SACH;
            return PartialView(sachNXB);
        }

        public ActionResult SearchPartial()
        {
            return PartialView();
        }

        public ActionResult SearchBuy(FormCollection collection)
        {
            var search = collection["keyWord"].ToLower();
            var ds = from SACH in db.SACHes where SACH.Tensach.ToLower().Contains(search) select SACH;
            ViewBag.keyWordSearch = collection["keyWord"];
            return View(ds);
        }
    }
}

TNLBook/Views/Buy/Chude.cshtml
@model IEnumerable<TNLBook.Models.CHUDE>

<nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
        <a href="@Url.Action("Index", "Buy")" class="nav-item nav-link">
            Tất cả
        </a>
        @foreach (var item in Model)
        {
            <a href="@Url.Action("SPTheoChude", "Buy", new {id = item.MaCD})" class="nav-item nav-link">
                @item.TenChuDe
            </a>
        }
    </div>
</nav>

TNLBook/Views/Buy/Detail.cshtml
@model TNLBook.Models.SACH

@{
    ViewBag.Title = "Chi tiết Sách";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">CHI TIẾT SẢN PHẨM</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="@Url.Action("Index", "Home")">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Chi tiết</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<div style="display: flex;">
    <div>
        <dl class="dl-horizontal">
            <dd>
                <img style="width: 300px;height: 450px;" src="~/img/@Html.DisplayFor(model => model.Anhbia)" />
            </dd>
        </dl>
    </div>
    <div style="padding: 5%;">
        <dl class="dl-horizontal">

            <dd style="color: red; font-size:25px;">
                @Html.DisplayFor(model => model.Tensach)
            </dd>

            <dt>
                Nhà xuất bản
            </dt>

            <dd style="color: red;">
                @Html.DisplayFor(model => model.NHAXUATBAN.TenNXB)
            </dd>

            <dt>
                Giá bán
            </dt>

            <dd style="color: red;">
                @String.Format("{0:0,0}", Model.Giaban) VNĐ
            </dd>

            <dt>
                Mô tả
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Mota)
            </dd>

        </dl>
        <div class="card-footer d-flex justify-content-between bg-light border">
            @if (Model.Soluongton > 0)
            {
                <a href="@Url.Action("ThemGiohang", "Cart", new { @iMasach = @Model.Masach, @strURL=Request.Url.ToString() })" class="btn btn-sm text-dark p-0">
                    <i class="fas fa-shopping-cart text-danger mr-1"></i>Thêm giỏ hàng
                </a>
            }
            else
            {
                <b style="color:red;">Hết hàng</b>
            }
        </div>
    </div>
</div>

TNLBook/Views/Buy/Index.cshtml
@using TNLBook.Models
@using PagedList.Mvc;
@model PagedList.PagedList<SACH>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">DANH MỤC SẢN PHẨM</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="@Url.Action("Index", "Home")">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Mua hàng</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-12">
            <!-- NXB Start -->
            <div class="border-bottom mb-4 pb-4">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-success text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Nhà xuất bản</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                @Html.Action("NXB", "Buy")
            </div>
            <!-- NXB End -->
        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">

                        <div class="col-lg-6 col-6 text-left">
                            @Html.Action("SearchPartial", "Buy")
                        </div>

                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                Sort by
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item" href="#">Latest</a>
                                <a class="dropdown-item" href="#">Popularity</a>
                                <a class="dropdown-item" href="#">Best Rating</a>
                            </div>
                        </div>
                    </div>
                </div>

                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <img style="height: 330px;" class="img-fluid w-100" src="~/img/@Html.DisplayFor(modelItem => item.Anhbia)" alt="">
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3">
                                    @Html.DisplayFor(modelItem => item.Tensach)
                                </h6>
                                <div class="d-flex justify-content-center">
                                    <h6>@String.Format("{0:0,0}", item.Giaban) VNĐ</h6>
                                    <h6 class="text-muted ml-2"><del>@String.Format("{0:0,0}", item.Giaban) VNĐ</del></h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a href="@Url.Action("Detail", "Buy", new { id = item.Masach })" class="btn btn-sm text-dark p-0">
                                    <i class="fas fa-eye text-danger mr-1"></i>Chi tiết
                                </a>
                                @if (item.Soluongton > 0)
                                {
                                    <a href="@Url.Action("ThemGiohang", "Cart", new { @iMasach = item.Masach, @strURL=Request.Url.ToString() })" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-danger mr-1"></i>Thêm giỏ hàng</a>
                                }
                                else
                                {
                                    <b style="color:red;">Hết hàng</b>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->
@* Tạo liên kết các trang *@
Trang @(Model.PageCount<Model.PageNumber?0:Model.PageNumber)/@Model.PageCount;

<div class="MenuTrang">
    @Html.PagedListPager(Model, page => Url.Action("Index", new { page = page }))
</div>

<style>
    .MenuTrang {
        display: flex;
        justify-content: center;
    }

        .MenuTrang li {
            display: inline;
            border: 1px solid;
            border-radius: 10px;
            padding: 5px 15px;
            margin: 2px;
        }

            .MenuTrang li.active {
                background-color: #4CAF50;
                color: white;
                border: 1px solid #4CAF50;
            }
</style>

TNLBook/Views/Buy/NXB.cshtml
@model IEnumerable<TNLBook.Models.NHAXUATBAN>

<nav class="collapse show navbar navbar-vertical navbar-light align-items-start p-0 border border-top-0 border-bottom-0" id="navbar-vertical">
    <div class="navbar-nav w-100 overflow-hidden" style="height: 410px">
        <a href="@Url.Action("Index", "Buy")" class="nav-item nav-link">
            Tất cả
        </a>
        @foreach (var item in Model)
        {
            <input type="checkbox" class="custom-control-input" checked id="nxb">
            <a href="@Url.Action("SPTheoNXB", "Buy", new {id = item.MaNXB})" class="nav-item nav-link">
                @item.TenNXB
            </a>
        }
    </div>
</nav>

TNLBook/Views/Buy/SPTheoNXB.cshtml
@model IEnumerable<TNLBook.Models.SACH>

@{
    ViewBag.Title = "SP Theo Nhà Xuất Bản";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">DANH MỤC SẢN PHẨM</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="@Url.Action("Index", "Home")">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Mua hàng</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-12">
            <!-- NXB Start -->
            <div class="border-bottom mb-4 pb-4">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-success text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Nhà xuất bản</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                @Html.Action("NXB", "Buy")
            </div>
            <!-- NXB End -->
        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">

                        <div class="col-lg-6 col-6 text-left">
                            @Html.Action("SearchPartial", "Buy")
                        </div>

                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                Sort by
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item" href="#">Latest</a>
                                <a class="dropdown-item" href="#">Popularity</a>
                                <a class="dropdown-item" href="#">Best Rating</a>
                            </div>
                        </div>
                    </div>
                </div>

                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <img style="height: 330px;" class="img-fluid w-100" src="~/img/@Html.DisplayFor(modelItem => item.Anhbia)" alt="">
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3">
                                    @Html.DisplayFor(modelItem => item.Tensach)
                                </h6>
                                <div class="d-flex justify-content-center">
                                    <h6>@String.Format("{0:0,0}", item.Giaban) VNĐ</h6>
                                    <h6 class="text-muted ml-2"><del>@String.Format("{0:0,0}", item.Giaban) VNĐ</del></h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a href="@Url.Action("Detail", "Buy", new { id = item.Masach })" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-success mr-1"></i>Chi tiết</a>
                                @if (item.Soluongton > 0)
                                {
                                    <a href="@Url.Action("ThemGiohang", "Cart", new { @iMasach = item.Masach, @strURL=Request.Url.ToString() })" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-danger mr-1"></i>Thêm giỏ hàng</a>
                                }
                                else
                                {
                                    <b style="color:red;">Hết hàng</b>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->

TNLBook/Views/Buy/SPTheochude.cshtml
@model IEnumerable<TNLBook.Models.SACH>

@{
    ViewBag.Title = "SP Theo Chủ Đề";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">DANH MỤC SẢN PHẨM</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="@Url.Action("Index", "Home")">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Mua hàng</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-12">
            <!-- NXB Start -->
            <div class="border-bottom mb-4 pb-4">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-success text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Nhà xuất bản</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                @Html.Action("NXB", "Buy")
            </div>
            <!-- NXB End -->
        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">

                        <div class="col-lg-6 col-6 text-left">
                            @Html.Action("SearchPartial", "Buy")
                        </div>

                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                Sort by
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item" href="#">Latest</a>
                                <a class="dropdown-item" href="#">Popularity</a>
                                <a class="dropdown-item" href="#">Best Rating</a>
                            </div>
                        </div>
                    </div>
                </div>

                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <img style="height: 330px;" class="img-fluid w-100" src="~/img/@Html.DisplayFor(modelItem => item.Anhbia)" alt="">
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3">
                                    @Html.DisplayFor(modelItem => item.Tensach)
                                </h6>
                                <div class="d-flex justify-content-center">
                                    <h6>@String.Format("{0:0,0}", item.Giaban) VNĐ</h6>
                                    <h6 class="text-muted ml-2"><del>@String.Format("{0:0,0}", item.Giaban) VNĐ</del></h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a href="@Url.Action("Detail", "Buy", new { id = item.Masach })" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-danger mr-1"></i>Chi tiết</a>
                                @if (item.Soluongton > 0)
                                {
                                    <a href="@Url.Action("ThemGiohang", "Cart", new { @iMasach = item.Masach, @strURL=Request.Url.ToString() })" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-danger mr-1"></i>Thêm giỏ hàng</a>
                                }
                                else
                                {
                                    <b style="color:red;">Hết hàng</b>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->

TNLBook/Views/Buy/SearchBuy.cshtml
@model IEnumerable<TNLBook.Models.SACH>
@{
    ViewBag.Title = "Search";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

<!-- Page Header Start -->
<div class="container-fluid bg-secondary mb-5">
    <div class="d-flex flex-column align-items-center justify-content-center" style="min-height: 300px">
        <h1 class="font-weight-semi-bold text-uppercase mb-3">DANH MỤC SẢN PHẨM</h1>
        <div class="d-inline-flex">
            <p class="m-0"><a href="@Url.Action("Index", "Home")">Home</a></p>
            <p class="m-0 px-2">-</p>
            <p class="m-0">Mua hàng</p>
        </div>
    </div>
</div>
<!-- Page Header End -->
<!-- Shop Start -->
<div class="container-fluid pt-5">
    <div class="row px-xl-5">
        <!-- Shop Sidebar Start -->
        <div class="col-lg-3 col-md-12">
            <!-- NXB Start -->
            <div class="border-bottom mb-4 pb-4">
                <a class="btn shadow-none d-flex align-items-center justify-content-between bg-success text-white w-100" data-toggle="collapse" href="#navbar-vertical" style="height: 65px; margin-top: -1px; padding: 0 30px;">
                    <h6 class="m-0">Nhà xuất bản</h6>
                    <i class="fa fa-angle-down text-dark"></i>
                </a>
                @Html.Action("NXB", "Buy")
            </div>
            <!-- NXB End -->
        </div>
        <!-- Shop Sidebar End -->
        <!-- Shop Product Start -->
        <div class="col-lg-9 col-md-12">
            <div class="row pb-3">
                <div class="col-12 pb-1">
                    <div class="d-flex align-items-center justify-content-between mb-4">

                        <div class="col-lg-6 col-6 text-left">
                            @Html.Action("SearchPartial", "Buy")
                        </div>

                        <div class="dropdown ml-4">
                            <button class="btn border dropdown-toggle" type="button" id="triggerId" data-toggle="dropdown" aria-haspopup="true"
                                    aria-expanded="false">
                                Sort by
                            </button>
                            <div class="dropdown-menu dropdown-menu-right" aria-labelledby="triggerId">
                                <a class="dropdown-item" href="#">Latest</a>
                                <a class="dropdown-item" href="#">Popularity</a>
                                <a class="dropdown-item" href="#">Best Rating</a>
                            </div>
                        </div>
                    </div>
                </div>

                @foreach (var item in Model)
                {
                    <div class="col-lg-4 col-md-6 col-sm-12 pb-1">
                        <div class="card product-item border-0 mb-4">
                            <div class="card-header product-img position-relative overflow-hidden bg-transparent border p-0">
                                <img style="height: 330px;" class="img-fluid w-100" src="~/img/@Html.DisplayFor(modelItem => item.Anhbia)" alt="">
                            </div>
                            <div class="card-body border-left border-right text-center p-0 pt-4 pb-3">
                                <h6 class="text-truncate mb-3">
                                    @Html.DisplayFor(modelItem => item.Tensach)
                                </h6>
                                <div class="d-flex justify-content-center">
                                    <h6>@String.Format("{0:0,0}", item.Giaban) VNĐ</h6>
                                    <h6 class="text-muted ml-2"><del>@String.Format("{0:0,0}", item.Giaban) VNĐ</del></h6>
                                </div>
                            </div>
                            <div class="card-footer d-flex justify-content-between bg-light border">
                                <a href="@Url.Action("Detail", "Buy", new { id = item.Masach })" class="btn btn-sm text-dark p-0"><i class="fas fa-eye text-danger mr-1"></i>Chi tiết</a>
                                @if (item.Soluongton > 0)
                                {
                                    <a href="@Url.Action("ThemGiohang", "Cart", new { @iMasach = item.Masach, @strURL=Request.Url.ToString() })" class="btn btn-sm text-dark p-0"><i class="fas fa-shopping-cart text-danger mr-1"></i>Thêm giỏ hàng</a>
                                }
                                else
                                {
                                    <b style="color:red;">Hết hàng</b>
                                }
                            </div>
                        </div>
                    </div>
                }
            </div>
        </div>
        <!-- Shop Product End -->
    </div>
</div>
<!-- Shop End -->

TNLBook/Views/Buy/SearchPartial.cshtml
@using (Html.BeginForm("SearchBuy", "Buy"))
{
    @Html.ValidationSummary(true)
    <div class="input-group">
        <input type="text" class="form-control" name="keyWord" value="@ViewBag.keyWordSearch" placeholder="Tìm kiếm . . .">
        <button class="btn btn-outline-success"><i class="fa fa-search"></i></button>
    </div>
}