TNLBook/Controllers/NguoidungController.cs
using System;
using System.Collections.Generic;
using System.Collections.ObjectModel;
using System.Drawing;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using TNLBook.Models;

namespace TNLBook.Controllers
{
    public class NguoidungController : Controller
    {
        SaleBookEntities1 db = new SaleBookEntities1();
        // GET: Nguoidung
        public ActionResult Index()
        {
            return View();
        }

        [HttpGet]
        public ActionResult Dangky()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Dangky(FormCollection collection, KHACHHANG khach)
        {
            var hoten = collection["HotenKH"];
            var tendn = collection["TenDN"];
            var mk = collection["MatKhau"];
            var xnmk = collection["XNMatKhau"];
            var email = collection["Email"];
            var diachi = collection["DiaChi"];
            var dt = collection["DienThoai"];
            var ngaysinh = string.Format("{0:MM/dd/yyyy}", collection["NgaySinh"]);

            if (String.IsNullOrEmpty(hoten))
            {
                ViewData["Loi1"] = "Họ tên khách hàng không được để trống!";
            }
            else if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi2"] = "Phải nhập tên đăng nhập!";
            }
            else if (String.IsNullOrEmpty(mk))
            {
                ViewData["Loi3"] = "Phải nhập mật khẩu!";
            }
            else if (String.IsNullOrEmpty(xnmk))
            {
                ViewData["Loi4"] = "Phải nhập lại mật khẩu!";
            }
            else if (String.IsNullOrEmpty(email))
            {
                ViewData["Loi5"] = "Phải nhập Email!";
            }
            else if (String.IsNullOrEmpty(dt))
            {
                ViewData["Loi6"] = "Phải nhập số điện thoại!";
            }
            else
            {
                khach.HoTen = hoten;
                khach.Taikhoan = tendn;
                khach.Matkhau = mk;
                khach.DiachiKH = diachi;
                khach.Email = email;
                khach.DienthoaiKH = dt;
                khach.Ngaysinh = DateTime.Parse(ngaysinh);
                db.KHACHHANGs.Add(khach);
                db.SaveChanges();
                return RedirectToAction("Dangnhap");
            }
            return this.Dangky();
        }

        [HttpGet]
        public ActionResult Dangnhap()
        {
            return View();
        }

        [HttpPost]
        public ActionResult Dangnhap(FormCollection collection)
        {
            // gán các giá trị người dùng nhập liệu cho các biến
            var tendn = collection["TenDN"];
            var mk = collection["MatKhau"];
            if (String.IsNullOrEmpty(tendn))
            {
                ViewData["Loi1"] = "Phải nhập tên đăng nhập!";
            }
            else if (String.IsNullOrEmpty(mk))
            {
                ViewData["Loi2"] = "Phải nhập mật khẩu!";
            }
            else
            {
                // gán giá trị cho đối tượng được tạo mới (kh)
                KHACHHANG kh = db.KHACHHANGs.SingleOrDefault(n => n.Taikhoan == tendn && n.Matkhau == mk);
                if (kh != null)
                {
                    ViewBag.Thongbao = "Chúc mừng đăng nhập thành công!";
                    Session["Taikhoan"] = kh;
                    Session["User"] = kh.Taikhoan;
                    return RedirectToAction("Index", "Home");
                }
                else
                    ViewBag.Thongbao = "Tên đăng nhập hoặc mật khẩu không đúng!";
            }
            return View();
        }

        public ActionResult Dangxuat()
        {
            Session["Taikhoan"] = null;
            return RedirectToAction("Index", "Home");
        }

    }
}

TNLBook/Views/Nguoidung/Dangky.cshtml
@model TNLBook.Models.KHACHHANG

@{
    ViewBag.Title = "Đăng Ký";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">
    <title>Register - TNLBook Book Store</title>

    <!-- Favicon -->
    <link href="~/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/www/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/www/css/style.css" rel="stylesheet">
</head>
<body>

    <div class="alert alert-info" style="text-align:center; font-size:35px;">
        <strong>ĐĂNG KÝ THÀNH VIÊN</strong>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
            <table align="center">
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <tr style="height:40px;">
                        <td>Họ tên khách hàng:</td>
                        <td>
                            <input type="text" name="HoTenKH" placeholder="Nhập họ tên!" />
                            @ViewData["Loi1"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Tên đăng nhập:</td>
                        <td>
                            <input type="text" name="TenDN" placeholder="Nhập tên đăng nhập!" />
                            @ViewData["Loi2"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Mật khẩu:</td>
                        <td>
                            <input type="password" name="MatKhau" placeholder="Hãy nhập mật khẩu!" />
                            @ViewData["Loi3"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Xác nhận mật khẩu:</td>
                        <td>
                            <input type="password" name="XNMatKhau" placeholder="Xác nhận lại mật Khẩu!" />
                            @ViewData["Loi4"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Email:</td>
                        <td>
                            <input type="text" name="Email" placeholder="Nhập Email của bạn!" />
                            @ViewData["Loi5"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Địa chỉ:</td>
                        <td>
                            @Html.TextBox("DiaChi")
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Điện thoại:</td>
                        <td>
                            <input type="text" name="DienThoai" placeholder="Nhập số điện thoại!" />
                            @ViewData["Loi6"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td>Ngày sinh:</td>
                        <td>
                            <input type="date" name="NgaySinh" />
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td></td>
                        <td>
                            <input class="btn btn-success" type="submit" value="Đăng ký" />
                            <a href="@Url.Action("Index", "Home")" class="btn btn-warning">Trang chủ</a>
                        </td>
                    </tr>
                }
            </table>
        </div>
        <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
            <img style="width: 700px;" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                 class="img-fluid" alt="Sample image">
        </div>
    </div>

</body>
</html>

TNLBook/Views/Nguoidung/Dangnhap.cshtml
@{
    ViewBag.Title = "Đăng nhập";
    Layout = null;
}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <meta content="width=device-width, initial-scale=1.0" name="viewport">
    <meta content="Free HTML Templates" name="keywords">
    <meta content="Free HTML Templates" name="description">
    <title>Login - TNLBook Book Store</title>

    <!-- Favicon -->
    <link href="~/favicon.ico" rel="icon">

    <!-- Google Web Fonts -->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@100;200;300;400;500;600;700;800;900&display=swap" rel="stylesheet">

    <!-- Font Awesome -->
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.10.0/css/all.min.css" rel="stylesheet">

    <!-- Libraries Stylesheet -->
    <link href="~/www/lib/owlcarousel/assets/owl.carousel.min.css" rel="stylesheet">

    <!-- Customized Bootstrap Stylesheet -->
    <link href="~/www/css/style.css" rel="stylesheet">
</head>
<body>

    <div class="alert alert-info" style="text-align:center; font-size:35px;">
        <strong>ĐĂNG NHẬP</strong>
    </div>
    <div class="alert alert-success">
        <strong>@ViewBag.Thongbao</strong>
    </div>
    <div class="row justify-content-center">
        <div class="col-md-10 col-lg-6 col-xl-5 order-2 order-lg-1">
            <table align="center">
                @using (Html.BeginForm())
                {
                    @Html.ValidationSummary(true)
                    <tr style="height:40px;">
                        <td>Tên đăng nhập:</td>
                        <td>
                            <input type="text" name="TenDN" placeholder="Nhập tên tài khoản!" />
                            @ViewData["Loi1"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td align="right">Mật khẩu:</td>
                        <td>
                            @Html.Password("MatKhau")
                            @ViewData["Loi2"]
                        </td>
                    </tr>
                    <tr style="height:40px;">
                        <td></td>
                        <td>
                            <input class="btn btn-info" type="submit" value="Đăng nhập" />
                            <a href="@Url.Action("Index", "Home")" class="btn btn-warning">Trang chủ</a>
                        </td>
                    </tr>
                }
            </table>
            <br />
            <h5 align="center">Bạn chưa có tài khoản? <a style="color:red;" href="@Url.Action("Dangky", "Nguoidung")">Đăng ký</a></h5>

        </div>
        <div class="col-md-10 col-lg-6 col-xl-7 d-flex align-items-center order-1 order-lg-2">
            <img style="width: 700px;" src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-registration/draw1.webp"
                 class="img-fluid" alt="Sample image">
        </div>
    </div>

</body>
</html>